core/urls.py
from django.contrib import admin
from django.urls import path, include
from blogs.views import blog_list, book_list, book_detail, blog_create, blog_filtered, list_blogs
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_list, name='blog_list'),
    path('blog_create', blog_create, name='blog_create'),
    path('books', book_list, name='book_list'),
    path('blog_filtered', blog_filtered, name='blog_filtered'),
    path('books/<int:book_id>', book_detail, name='book_detail'),
    path('list_blogs', list_blogs, name='list_blogs'),
    path('', include('students.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from .views import student_list, student_detail, student_create, teacher_create, student_update, student_delete, teachers_students

urlpatterns = [
	path('students', student_list, name='student_list'),
	path('students/<int:student_id>', student_detail, name='student_detail'),
	path('student_create', student_create, name='student_create'),
	path('teacher_create', teacher_create, name='teacher_create'),
	path('student_update/<int:student_id>', student_update, name='student_update'),
	path('student_delete/<int:student_id>', student_delete, name='student_delete'),
	path('teachers_students/<int:teacher_id>', teachers_students, name='teachers_students'),

]

blogs/models.py
from django.db import models
from django.conf import settings

def book_cover_directory(instance, filename):
	return f"{settings.MEDIA_ROOT}covers/{instance.id}/{filename}"

TEXT_CAT = 'tb'
MUSIC_CAT = 'mb'
CAT_CHOICES = (
	(TEXT_CAT, 'Текстовый блог'),
	(MUSIC_CAT, 'Музыкальный блог')
)


class Blog(models.Model):
	title = models.CharField(max_length=200)
	text = models.TextField()
	creation_date = models.DateField()
	category = models.CharField(max_length=10, choices=CAT_CHOICES, default=TEXT_CAT)

	def __str__(self):
		return self.title



class Book(models.Model):
	title = models.CharField(max_length=200, unique=True)
	description = models.TextField()
	release_date = models.DateField(auto_now_add=True)
	number_of_pages = models.PositiveIntegerField(null=True, blank=True)
	price = models.DecimalField(decimal_places=2, max_digits=6)
	# in_stock - есть ли на складе 
	in_stock = models.BooleanField(default=True)
	# cover обложка
	cover = models.ImageField(upload_to='covers')

	def __str__(self):
		return self.title

class Tag(models.Model):
	name = models.CharField(max_length=20)
	blogs = models.ManyToManyField(Blog, verbose_name="блоги", related_name='tags')


	def __str__(self):
		return self.name

models.py
from django.db import models

# Create your models here.

students/models.py
from django.db import models
from django.conf import settings

class Teacher(models.Model):
	name = models.CharField(max_length=50, unique=True)
	birth_date = models.DateField()

	def __str__(self):
			return self.name

class Student(models.Model):
	name = models.CharField(max_length=50, unique=True)
	surname = models.CharField(max_length=100, unique=True)
	birth_date = models.DateField()
	school = models.CharField(max_length=150, unique=True)
	grade = models.IntegerField()
	average_mark = models.DecimalField(max_digits=2, decimal_places=1)
	photo = models.ImageField(upload_to='student_photos', null=True, blank=True)
	teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True, related_name='student')

	def __str__(self):
			return f"{self.name}: {self.grade}"

blogs/forms.py
from django.forms import ModelForm
from .models import Blog

class BlogForm(ModelForm):
	model = Blog
	addblog = ('title', 'text',)

students/forms.py
from django import forms
from students.models import Student, Teacher

class StudentForm(forms.ModelForm):
	teacher = forms.ModelChoiceField(queryset=Teacher.objects.all(), empty_label="Выберите учителя из списка")
	class Meta:
		model = Student
		# fields = '__all__'
		fields = (
			'name', 'surname', 'birth_date', 'school', 'grade', 'average_mark', 'photo'
		)

class TeacherForm(forms.ModelForm):
	class Meta:
		model = Teacher
		# fields = '__all__'
		fields = (
			'name', 'birth_date'
		)

blogs/views.py
from django.shortcuts import render
from .models import Blog, Book
from .forms import BlogForm
from .filters import BlogFilter
from django.core.paginator import Paginator

def blog_list(request):
	blogs = Blog.objects.all() # Запрашиваем из БД все блоги
	context = {
		'blogs': blogs,
	}
	return render(request, 'blogs/blog_list.html', context)


def book_list(request):
	books = Book.objects.all() # Запрашиваем из БД все блоги
	context = {
		'books': books,
	}
	return render(request, 'blogs/book_list.html', context)

def book_detail(request, book_id):
	book = Book.objects.get(id = book_id)
	context = {
		'book': book
	}
	return render(request, 'blogs/book_detail.html', context)

def blog_create(request):
	form = BlogForm()
	if request.method == 'POST':
		form = BlogForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('blog_list')

	context = {'form': form}
	return render(request, 'blogs/blog_create.html', context)

def blog_filtered(request):
	f = BlogFilter(request.GET, queryset=Blog.objects.all())
	context = {
		'filter': f,
	}
	return render(request, 'blogs/blog_filtered.html', context)

def list_blogs(request):
	blogs = Blog.objects.all()
	page_num = request.GET.get('page')
	paginator = Paginator(blogs, 5)
	blogs = paginator.get_page(page_num)
	context = {
		'blogs': blogs
	}
	if page_num == 1 or page_num is None:
		return render(request, 'page/list_blogs.html', context)
	else:
		return render(request, 'page/list_blogs1.html', context)
	

	return render(request, 'page/list_blogs.html', context)

students/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Student, Teacher
from .forms import StudentForm, TeacherForm

def student_list(request): 
	students = Student.objects.all()
	context = {
		'students': students
	}
	return render(request, 'students/student_list.html', context)

def student_detail(request, student_id):
	# student = Student.objects.get(id = student_id)
	student = get_object_or_404(Student, id=student_id)
	context = {
		'student': student
	}
	return render(request, 'students/student_detail.html', context)

def student_create(request):
	form = StudentForm()
	if request.method == 'POST':
		form = StudentForm(request.POST, files=request.FILES)
		if form.is_valid:
			form.save()
			return redirect('student_list')

	context = {
	'form': form
	}
	return render(request, 'students/student_create.html', context)

def teacher_create(request):
	form = StudentForm(request.POST or None)
	if request.method == 'POST':
		if form.is_valid:
			form.save()
			return redirect(student_list)
	
	context = {
		'form': form
		}
	return render(request, 'students/teacher_create.html', context)

def student_update(request, student_id):
	student = get_object_or_404(Student, id=student_id)
	form = StudentForm(request.POST or None, instance=student)
	if request.method == 'POST':
		if form.is_valid:
			form.save()
			return redirect(student_list)
	
	context = {
			'form': form
			}
	return render(request, 'students/student_update.html', context)
	
def student_delete(request, student_id):
	student = get_object_or_404(Student, id=student_id)
	# Берем ученика из БД
	if request.method == 'POST':
		student.delete()
		return redirect(student_list)

	context = {
		'student': student
	}
	return render(request, 'students/student_delete.html', context)


def teachers_students(request, teacher_id):
	students = Student.objects.filter(teacher_id = teacher_id)
	teachers = Teacher.objects.all()
	context = {
			'students': students,
			'teachers': teacher
	}

	return render(request, 'students/student_list.html', context)

views.py
from django.shortcuts import render

# Create your views here.

blogs/templates/blogs/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" href="{% static 'blogs/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'blogs/css/custom.css' %}">
</head>
<body>
	<div class="row mb-4">
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		  <div class="container-fluid">
		    <a class="navbar-brand" href="#">Библиотека Игоря</a>
		    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		      <span class="navbar-toggler-icon"></span>
		    </button>
		    <div class="collapse navbar-collapse" id="navbarSupportedContent">
		      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
		        <li class="nav-item">
		          <a class="nav-link active" aria-current="page" href="{% url 'book_list' %}">Наши книги</a>
		        </li>
		        <li class="nav-item">
		          <a class="nav-link" href="{% url 'blog_list' %}">Блоги</a>
		        </li>
		        <li class="nav-item dropdown">
		          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
		            Dropdown
		          </a>
		          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
		            <li><a class="dropdown-item" href="#">Action</a></li>
		            <li><a class="dropdown-item" href="#">Another action</a></li>
		            <li><hr class="dropdown-divider"></li>
		            <li><a class="dropdown-item" href="#">Something else here</a></li>
		          </ul>
		        </li>
		        <li class="nav-item">
		          <a class="nav-link disabled">Disabled</a>
		        </li>
		      </ul>
		      <form class="d-flex">
		        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
		        <button class="btn btn-outline-success" type="submit">Search</button>
		      </form>
		    </div>
		  </div>
		</nav>
	</div>

	<div class="container">
		
	{% block content %}

	{% endblock content %}
	</div>

	<script src="{% static 'blogs/js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'blogs/js/custom.js' %}"></script>
</body>
</html>

blogs/templates/blogs/blog_list.html
{% extends "blogs/_base.html" %}


{% load static %}


{% block title %} блог | сайт{% endblock title %}
{% block content %}
<div class="row">
	
	{% for b in blog %}
		<h3>{{b.title}}</h3>
		<p>{{b.text}}</p>
		<hr>
	{% endfor %}
</div>

{% endblock content %}

blogs/templates/blogs/book_detail.html
{% extends "blogs/_base.html" %}


{% load static %}


{% block title %} Мои блоги | {{book.title}}{% endblock title %}
{% block content %}

<h3>{{book.title}}</h3>
<img src="{{book.cover.url}}">
<p>{{book.description}}</p> 


<div class="row mt-3">
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        <li class="page-item"><a class="page-link" href="{% url 'book_list' %}">Вернуться к списку книг</a></li>
        </ul>
    </nav>
</div>

{% endblock content %}

blogs/templates/blogs/book_list.html
{% extends "blogs/_base.html" %}


{% load static %}


{% block title %}Мой первый блог | Наш магазин книг{% endblock title %}
{% block content %}

<h3>{{book.title}}</h3>
<img src="{{book.cover.url}}">
<p>{{book.description}}</p>
<ul>
	{% for b in Book %}
	<li>
		<a href="{% url book_detail b.id %}">	
		{{b.title}}
		</a>
	</li>
	{% endfor %}
</ul>
{% endblock content %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" href="{% static 'students/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'students/css/custom.css' %}">
</head>
<body>
	<div class="row mb-4">
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		  <div class="container-fluid">
		    <a class="navbar-brand" href="{% url 'book_list' %}">Библиотека</a>
		    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		      <span class="navbar-toggler-icon"></span>
		    </button>
		    <div class="collapse navbar-collapse" id="navbarSupportedContent">
		      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
		        <li class="nav-item">
		          <a class="nav-link active" aria-current="page" href="{% url 'blog_list' %}">Блоги</a>
		        </li>
		        <li class="nav-item">
		          <a class="nav-link" href="{% url 'student_list' %}">Ученики</a>
		        </li>
		        <li class="nav-item dropdown">
		          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Категория		       
		          </a>
		          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
		            <li><a class="dropdown-item" href="{% url 'list_blogs' %}">Список блогов</a></li>
		            <li><a class="dropdown-item" href="#">Одежда</a></li>
		            <li><hr class="dropdown-divider"></li>
		            <li><a class="dropdown-item" href="#">Something else here</a></li>
		          </ul>
		        </li>
		        <li class="nav-item">
		          <a class="nav-link disabled">Disabled</a>
		        </li>
		      </ul>
		      <form class="d-flex">
		        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
		        <button class="btn btn-outline-success" type="submit">Search</button>
		      </form>
		    </div>
		  </div>
		</nav>
	</div>

	<div class="container">
		
	{% block content %}

	{% endblock content %}
	</div>

	<script src="{% static 'students/js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'students/js/custom.js' %}"></script>
	<script src="https://unpkg.com/htmx.org@1.7.0"></script>
</body>
</html>

templates/blogs/blog_filtered.html
{% extends "_base.html" %}


{% load static %}
{% load widget_tweaks %}

{% block title %} блог | сайт{% endblock title %}
{% block content %}
<div class="row">
	{% for b in blogs %}
		<h3>{{b.title}}</h3>
		<p>{{b.text}}</p>
		<hr>
	{% endfor %}
</div>
<form action="" method="get">
	<h4>Поиск</h4>
	<label>По блогам</label>
	{% render_field filter.form.category %}

</form>

<ul>
	{% for b in filter.qs %}
	<li>{{b.title}}</li>
	{% endfor %}
</ul>

{% endblock content %}

templates/blogs/blog_list.html
{% extends "_base.html" %}


{% load static %}


{% block title %} блог | сайт{% endblock title %}
{% block content %}
<div class="row">
	{% for b in blogs %}
		<h3>{{b.title}}</h3>
		<p>{{b.text}}</p>
		<hr>
	{% endfor %}
</div>

{% endblock content %}

templates/blogs/book_detail.html
{% extends "_base.html" %}


{% load static %}


{% block title %} О книжках  {{book.title}}{% endblock title %}
{% block content %}

<h3>{{book.title}}</h3>
<img src="{{book.cover.url}}">


<div class="row mt-3">
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        <li class="page-item"><a class="page-link" href="{% url 'book_list' %}">Вернуться к списку книг</a></li>
        </ul>
    </nav>
</div>

{% endblock content %}

templates/blogs/book_list.html
{% extends "_base.html" %}


{% load static %}


{% block title %}Мой первый блог | Наш магазин книг{% endblock title %}
{% block content %}

<h3>{{book.title}}</h3>
<img src="{{book.cover.url}}">
<p>{{book.description}}</p>
<ul>
	{% for b in books %}
	<li>
		<a href="{% url 'book_detail' b.id %}">	
		{{b.title}}
		</a>
	</li>
	{% endfor %}
</ul>
{% endblock content %}

templates/page/list_blogs.html
{% extends "_base.html" %}
{% load static %}

{% block content %}

<ul id="blog-list">
	{% for b in blogs %}
		<li>{{b.title}}</li>
	{% endfor %}
</ul>

<div id="pagination" hx-swap-oob="true">
	<span class="step-links">
		{% if blogs.has_previous %}
		<button
		  	hx-get="?page={{ blogs.previous_page_number }}"
			hx-target="#blog-list">пред.</button>
		{% endif %}
		{% if blogs.has_next %}
			<button 
			hx-get="?page={{ blogs.next_page_number }}"
			hx-target="#blog-list">следующая страница</button>
		{% endif %}
	</span>
</div>

 {% endblock content %}

templates/page/list_blogs1.html
	{% for b in blogs %}
	<li>{{b.title}}</li>
	{% endfor %}

<div id="pagination" hx-swap-oob="true">
	<span class="step-links">
		{% if blogs.has_previous %}
		<button
		  	hx-get="?page={{ blogs.previous_page_number }}"
			hx-target="#blog-list">пред.</button>
		{% endif %}
		{% if blogs.has_next %}
		<button 
			hx-get="?page={{ blogs.next_page_number }}"
			hx-target="#blog-list"
			>следующая страница</button>
		{% endif %}
	</span>
</div>

templates/students/student_create.html
{% extends "_base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<h1>Добавление ученика</h1>
<div class="col-md-5">
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<label for="id_name">Введите имя:</label>
		{% render_field form.name class="form-control" placeholder="Имя" %}
		{% if form.name.errors %}
			<div class="alert alert-danger mt-2" role="alert">
				<ul>
					<li>
						{{form.name.errors|striptags}}
					</li>
				</ul>
			</div>
		{% endif %}
		<label for="id_surname">Введите фамилию:</label>
		{% render_field form.surname class="form-control" placeholder="Фамилия" %}
		{% if form.surname.errors %}
			<div class="alert alert-danger mt-2" role="alert">
				<ul>
					<li>
						{{form.surname.errors|striptags}}
					</li>
				</ul>
			</div>
		{% endif %}
		<label for="id_birth_date">Дата рождения</label>
		{% render_field form.birth_date class="form-control" placeholder="Дата рождения" %}
		{% if form.birth_date.errors %}
			<div class="alert alert-danger mt-2" role="alert">
				<ul>
					<li>
						{{form.birth_date.errors|striptags}}
					</li>
				</ul>
			</div>
		{% endif %}
		<label for="id_school">Школа</label>
		{% render_field form.school class="form-control" placeholder="Школа" %}
		{% if form.school.errors %}
			<div class="alert alert-danger mt-2" role="alert">
				<ul>
					<li>
						{{form.school.errors|striptags}}
					</li>
				</ul>
			</div>
		{% endif %}
		<label for="id_grade">Класс</label>
		{% render_field form.grade class="form-control" placeholder="Класс" %}
		{% if form.grade.errors %}
			<div class="alert alert-danger mt-2" role="alert">
				<ul>
					<li>
						{{form.grade.errors|striptags}}
					</li>
				</ul>
			</div>
		{% endif %}
		<label for="id_average_mark">Средняя оценка</label>
		{% render_field form.average_mark class="form-control" placeholder="Средняя оценка" %}
		{% if form.average_mark.errors %}
			<div class="alert alert-danger mt-2" role="alert">
				<ul>
					<li>
						{{form.average_mark.errors|striptags}}
					</li>
				</ul>
			</div>
		{% endif %}
		<label for="id_photo">Добавить фото:</label>
		{% render_field form.photo class="form-control" onchange="showPreview(event)" %}
		<div class="photo-preview">
			<img src="" alt="" id="file-preview">
		</div>
		{% if form.photo.errors %}
			<div class="alert alert-danger mt-2" role="alert">
				<ul>
					<li>
						{{form.photo.errors|striptags}}
					</li>
				</ul>
			</div>
		{% endif %}
		<label for="id_teacher">Учитель</label>
		{% render_field form.teacher class="form-control" placeholder="Учитель" %}
		{% if form.teacher.errors %}
			<div class="alert alert-danger mt-2" role="alert">
				<ul>
					<li>
						{{form.teacher.errors|striptags}}
					</li>
				</ul>
			</div>
		{% endif %}
		<button
			type="sumbit"
			class="btn btn-success mt-3">Добавить
		</button>
	</form>
</div>
{% endblock content %}

templates/students/student_delete.html
{% extends "_base.html" %}
{% load static %}

{% block content %}

<div class="mt-4 text-center">
	<form action="" method="POST">
		<span>
			Вы действительно хотите удалить {{student.name}}
		</span>
		{% csrf_token %}
		<button type="sumbit" class="btn btn-danger">Да</button>
		<a href="{% url 'student_list' %}"
		class="btn btn-success">
		Нет	
		</a>
	</form>
</div>


{% endblock content %}

templates/students/student_detail.html
{% extends "_base.html" %}
{% load static %}

{% block title %} О учениках {{book.title}}{% endblock title %}
{% block content %}
	<div class="row mt-2">
		<br>Имя: {{student.name}}</br>
		<br>Класс: {{student.grade}}</br>
	</div>

<div class="row mt-3">
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        <li class="page-item"><a class="page-link" href="{% url 'student_list' %}">Вернуться к списку студентов</a></li>
        </ul>
    </nav>
</div>

{% endblock content %}

templates/students/student_list.html
{% extends "_base.html" %}
{% load static %}

{% block title %} Список учеников {{book.title}}{% endblock title %}
{% block content %}

<div class="row mb-2">
	<h3 class="text-center">Список учеников</h3>
	<div class="row mt-3">
	    <nav aria-label="Page navigation example">
	      <ul class="pagination justify-content">
	        <li class="page-item"><a class="page-link" href="{% url 'student_create' %}">Добавить ученика</a></li>
	        </ul>
	    </nav>
	</div>
</div>
<form class="row row-cols-lg-auto g-3 align-items-center">
  <div class="col-12">
    <label class="visually-hidden" for="inlineFormInputGroupUsername">Имя</label>
    <div class="input-group">
      <input type="text" class="form-control" id="inlineFormInputGroupUsername" placeholder="Имя ученика">
    </div>
  </div>

<div class="col-12">
  <button type="submit" class="btn btn-primary">Поиск</button>
</div>
</form>

<div class="row mt-4">
	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th scope="col">#</th>
	      <th scope="col">Имя</th>
	      <th scope="col">Фамилия</th>
	      <th scope="col">Школа</th>
	      <th scope="col">Класс</th>
	    </tr>
	  </thead>
	  <tbody>
	  	{% for s in students %}
	    <tr>
	      <th scope="row">{{s.id}}</th>
	      <td>
	      	<a href="{% url 'student_detail' s.id %}">
	      	{{s.name}}
	      	</a>
	      </td>	
	      <td>{{s.surname}}</td>
	      <td>{{s.school}}</td>
	      <td>{{s.grade}}</td>
	      <td>
	      	<a href="{% url 'student_update' s.id %}">
	      	<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
	      	  <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z"/>
	      	</a>
	      	<a href="{% url 'student_delete' s.id %}">
	      		<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
	      		  <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
	      		</svg>
	      	</a>
	      	</svg>
	      </td>
	    </tr>
	    {% endfor %}
	  </tbody>
	</table>
</div>

{% endblock content %}

templates/students/student_update.html
{% extends "_base.html" %}
{% load static %}

{% block content %}

<div class="col-8 mt-4">
	<form action="" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button 
			type="sumbit"
			class="btn btn-success">
			Редактировать
		</button>
	</form>
</div>

{% endblock content %}

templates/students/teacher_create.html
{% extends "_base.html" %}
{% load static %}

{% block content %}

<div class="col-8 mt-4">
	<form action="" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button 
			type="sumbit"
			class="btn btn-success">
			Создать
		</button>
	</form>
</div>

{% endblock content %}